name: delft3dfmpy

channels:
  - conda-forge

dependencies:
  - fire
  - gdal>=2.4.1
  - geopandas
  - git
  - imod
  - matplotlib
  - netcdf4 
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - rasterio
  - rasterstats
  - scipy
  - setuptools_scm
  - tqdm
  - pip:
    - hkvsobekpy
