name: delft3dfmpy
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7.*
  - git
  - pip  
  - geopandas
  - rasterio  
  - imod  
  - numpy
  - scipy  
  - pandas  
  - matplotlib
  - pillow
  - rasterstats
  - tqdm
  - netcdf4 
  - descartes
  - contextily
  - pip:
    - hkvsobekpy
